apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: kube-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-system
      interval: 24h
  targetNamespace: kube-system
  values:
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
