apiVersion: v1
kind: Namespace
metadata:
  name: identity
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  url: https://codecentric.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 1m
  targetNamespace: identity
  values:
    replicas: 1
