apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-istio-proxy
  namespace: istio-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-virtual-services-controller
  namespace: istio-sandbox
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - list
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-virtual-services-controller
  namespace: istio-sandbox
subjects:
  - kind: ServiceAccount
    name: jupyter-istio-proxy
    namespace: istio-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-virtual-services-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: istio-sandbox
  labels:
    app: jupyterhub
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
      component: proxy
      release: RELEASE-NAME
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jupyterhub
        component: proxy
        release: RELEASE-NAME
    spec:
      serviceAccountName: jupyter-istio-proxy
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - proxy
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        - name: proxy
          command:
            - /proxy/jupyterhub-istio-proxy
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              value: bnZsR2tEQmVveGtKNFNjZmxwb043QjFGVnU2dWJoT0NadVRaRU1SMnoyU0tpc0phTTdRWmtlZjFQZExkUWlWNQ==
            - name: ISTIO_GATEWAY
              value: istio-gateway
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SUB_DOMAIN_HOST
              value: '*'
            - name: VIRTUAL_SERVICE_PREFIX
              value: jupyterhub
            - name: WAIT_FOR_WARMUP
              value: 'true'
            - name: CLUSTER_DOMAIN
              value: 'cluster.local'
          image: splunk/jupyterhub-istio-proxy:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: proxy-api
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 256M
            requests:
              cpu: 100m
              memory: 256M
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  namespace: istio-sandbox
spec:
  ports:
    - name: http
      port: 8001
      protocol: TCP
      targetPort: proxy-api
  selector:
    component: proxy
  type: ClusterIP
